export const PLATFORM = {
  name: 'DiDi',
  tagline: 'Browse local restaurants. Call to order.',
  currency: 'GHS',
  currencySymbol: '₵',
  supportEmail: 'support@didi.gh',
  supportPhone: '0592649039',
};

export const FOOD_CATEGORIES = [
  'Local',
  'Fast Food',
  'Grills',
  'Drinks',
  'Snacks',
  'Desserts',
  'Healthy',
  'Breakfast',
  'Seafood',
  'Pizza',
  'Rice Dishes',
  'Soups & Stews',
  'Street Food',
  'Bakery',
  'Vegetarian',
  'Vegan',
  'Coffee & Tea',
  'Noodles & Pasta',
  'International',
  'BBQ & Wings',
  'Juices & Smoothies',
  'Kids Menu',
  'Other',
] as const;

export type FoodCategory = typeof FOOD_CATEGORIES[number];

export const CATEGORY_ICONS: Record<string, string> = {
  Local:     '🍛',
  'Fast Food': '🍔',
  Grills:    '🔥',
  Drinks:    '🥤',
  Snacks:    '🍿',
  Desserts:  '🍰',
  Healthy:   '🥗',
  Breakfast: '🍳',
  Seafood:   '🦐',
  Pizza:     '🍕',
  'Rice Dishes': '🍚',
  'Soups & Stews': '🍲',
  'Street Food': '🌮',
  Bakery:    '🥐',
  Vegetarian: '🥬',
  Vegan:     '🌱',
  'Coffee & Tea': '☕',
  'Noodles & Pasta': '🍝',
  International: '🌍',
  'BBQ & Wings': '🍗',
  'Juices & Smoothies': '🧃',
  'Kids Menu': '🧒',
  Other:     '🍽️',
};
